#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "medshake"
name = "Medshake"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "8.1.4~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://www.medshake.app"
demo = "https://demo.example.com"
admindoc = "https://www.medshake.app/documentation-technique/environnement-de-production-necessaire-a-medshakeehr.html"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/MedShake/MedShakeEHR-base"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/MedShake/MedShakeEHR-base/archive/refs/tags/v8.1.4.tar.gz"
    sha256 = "75963686c8d7d2f7322620e7f57ceb409acec09fa81fbf8ff20f0cf47d8d7b33"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server, php8.2-dom, php8.2-mbstring, php8.2-mbstring, php8.2-pdo,  php8.2-bcmath, php8.2-gd, php8.2-intl, php8.2-curl, php8.2-zip, php8.2-xml, php8.2-imagick, php8.2-imap, php8.2-soap"
 
    [resources.database]
    type = "mysql"
